-- MySQL Script generated by MySQL Workbench
-- mar 26 may 2026 22:48:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parqueo_24_7_evidencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parqueo_24_7_evidencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parqueo_24_7_evidencia` ;
USE `parqueo_24_7_evidencia` ;

-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`persona` (
  `idpersona` INT NOT NULL,
  `uuid` VARCHAR(36) NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT NULL,
  `sexo` ENUM('M', 'F', 'O') NULL DEFAULT 'O',
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `tipo_persona` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `tipo_documento_UNIQUE` (`tipo_documento` ASC) VISIBLE,
  UNIQUE INDEX ` numero_documento_UNIQUE` (`numero_documento` ASC) VISIBLE,
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`usuario` (
  `idusuario` INT NOT NULL,
  `uuid` VARCHAR(45) NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(60) NOT NULL,
  ` fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_DATE,
  `creado_por` VARCHAR(30) NULL,
  `actualizado_por` VARCHAR(30) NULL,
  `eliminado_por` VARCHAR(30) NULL,
  `fecha_actualizacion` DATE NULL,
  `fecha_eliminacion` DATE NULL,
  `persona_id` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `usuariocolcontrasena_UNIQUE` (`contrasena` ASC) VISIBLE,
  UNIQUE INDEX `persona_id_UNIQUE` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `persona_id`
    FOREIGN KEY (`persona_id`)
    REFERENCES `parqueo_24_7_evidencia`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`cliente` (
  `idcliente` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `codigo_cliente` VARCHAR(45) NOT NULL,
  ` persona_id` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC) VISIBLE,
  UNIQUE INDEX ` persona_id_UNIQUE` (` persona_id` ASC) VISIBLE,
  CONSTRAINT `person_id`
    FOREIGN KEY (` persona_id`)
    REFERENCES `parqueo_24_7_evidencia`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.` vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.` vehiculo` (
  `id vehiculo` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `placa` VARCHAR(20) NOT NULL,
  `tipo_vehiculo` VARCHAR(20) NOT NULL,
  `marca` VARCHAR(20) NULL,
  `color` VARCHAR(20) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id vehiculo`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  INDEX `fk_ cliente_id_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `parqueo_24_7_evidencia`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`reserva` (
  `idreserva` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `tipo_solicitud` VARCHAR(30) NULL,
  `descripcion` VARCHAR(200) NULL,
  `estado_reserva` ENUM('pendiente', 'confirmada', 'cancelada') NULL DEFAULT 'pendiente',
  `fecha_` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_reserva_1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `parqueo_24_7_evidencia`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`parqueadero` (
  `idparqueadero` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idparqueadero`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`espacio_parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`espacio_parqueadero` (
  `idespacio_parqueadero` INT NOT NULL,
  `espacio_parqueadero` VARCHAR(36) NOT NULL,
  `numero_espacio` VARCHAR(4) NOT NULL,
  `precio_hora` DECIMAL(10,2) NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  `parqueadero_id` INT NOT NULL,
  PRIMARY KEY (`idespacio_parqueadero`),
  UNIQUE INDEX `espacio_parqueaderocol_UNIQUE` (`espacio_parqueadero` ASC) VISIBLE,
  UNIQUE INDEX `numero_espacio_UNIQUE` (`numero_espacio` ASC) VISIBLE,
  INDEX `fk_espacio_parqueadero_parqueadero_idx` (`parqueadero_id` ASC) VISIBLE,
  CONSTRAINT `fk_espacio_parqueadero_parqueadero`
    FOREIGN KEY (`parqueadero_id`)
    REFERENCES `parqueo_24_7_evidencia`.`parqueadero` (`idparqueadero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`ticket` (
  `idticket` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `numero_recibo` INT NOT NULL,
  `hora_entrada` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hora_salida` DATETIME NULL,
  `tarifa_aplicada` DECIMAL(10,2) NULL,
  `numero_espacio` VARCHAR(4) NOT NULL,
  `cliente_id` INT NOT NULL,
  `placa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idticket`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `numero_recibo_UNIQUE` (`numero_recibo` ASC) VISIBLE,
  INDEX `numero_espacio_idx` (`numero_espacio` ASC) VISIBLE,
  INDEX `fk_ticket_cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_ticket_vehiculo_idx` (`placa` ASC) VISIBLE,
  CONSTRAINT `numero_espacio`
    FOREIGN KEY (`numero_espacio`)
    REFERENCES `parqueo_24_7_evidencia`.`espacio_parqueadero` (`espacio_parqueadero`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `parqueo_24_7_evidencia`.`cliente` (`idcliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_vehiculo`
    FOREIGN KEY (`placa`)
    REFERENCES `parqueo_24_7_evidencia`.` vehiculo` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`pago` (
  `idpago` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `valor_pagado` DECIMAL(10,2) NOT NULL,
  `metodo_pago` VARCHAR(20) NOT NULL,
  `estado_pago` VARCHAR(20) NOT NULL,
  `numero_resibo` INT NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_ticket_idx` (`numero_resibo` ASC) VISIBLE,
  CONSTRAINT `fk_pago_ticket`
    FOREIGN KEY (`numero_resibo`)
    REFERENCES `parqueo_24_7_evidencia`.`ticket` (`numero_recibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo_24_7_evidencia`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo_24_7_evidencia`.`empresa` (
  `idempresa` INT NOT NULL,
  `uuid` VARCHAR(36) NOT NULL,
  `nit` VARCHAR(11) NOT NULL,
  `razon_social` VARCHAR(45) NOT NULL,
  `naturaleza_juridica` VARCHAR(30) NULL,
  `nombre_representante_legal` VARCHAR(60) NULL,
  `celular_representante_legal` VARCHAR(15) NULL,
  `email_representante_legal` VARCHAR(45) NULL,
  `parqueadero_id` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC) VISIBLE,
  INDEX `fk_empresa_parqueadero_idx` (`parqueadero_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_parqueadero`
    FOREIGN KEY (`parqueadero_id`)
    REFERENCES `parqueo_24_7_evidencia`.`parqueadero` (`idparqueadero`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
